### ISSUE TITLE
mongo add  prefix not work

### ISSUE THREAD

**Issue by Xiaocge** [mongodb/laravel-mongodb#1275]
![image](https://user-images.githubusercontent.com/18593080/29698503-783063d0-8988-11e7-8c19-845818e6363f.png)
not work

**Comment by 1034190174** [comment]
Have you solved it

**Comment by GromNaN** [comment]
Tracking this feature request in [PHPORM-82](https://jira.mongodb.org/browse/PHPORM-82)

**Comment by GromNaN** [comment]
Fixed by #2930 in 4.4.0
