### ISSUE TITLE
Does laravel-mongodb has passport support ?

### ISSUE THREAD

**Issue by majuansari** [mongodb/laravel-mongodb#1390]
I have been trying work with passport and mongodb. Do this package has passport support ? If not is any other solutions make it work with passport ?

Currently when I am running 

> php artisan passport:install

I am getting the following error

```
Encryption keys generated successfully.

In Connection.php line 451:
                                               
  Call to a member function prepare() on null  
```

**Comment by DMNSteve** [comment]
Hey @majuansari. Please see the implementation in this pull request https://github.com/jenssegers/laravel-mongodb/pull/1333

**Comment by majuansari** [comment]
@DMNSteve  Thank you. Seems like this has not been merged to the repo. Is there anyway I could use this or fix issue without editing the passport codebase ?

**Comment by DMNSteve** [comment]
You could use the fork at https://github.com/DMNSteve/laravel-mongodb.

Or you could fork the repository yourself and patch that pull request. :)

**Comment by LeonAlvarez** [comment]
@DMNSteve Im using your provider + classes adapted to extend MongoDB eloquent model, from your PR
but when I use the password credential type the  tokens user_id is always the first use on my DB, no matter wich credentials I use on the Auth process.

`public function createNewApiToken($name , $client_id , $scopes = [])
    {
        $token = $this->createToken($name, $scopes);
        $token_model = Token::find($token->token->id);
        $token_model->client_id = $client_id;
        $token_model->save();
        $token->token = $token_model;
        return $token;
    }`

Currently added that method and accesing it to auth, as a dirty fix ¿did you have any Issue with password grant auth type ?

**Comment by DMNSteve** [comment]
I didn't have any issues myself. What version of Passport are you using? I'd like to investigate a little further.

**Comment by LeonAlvarez** [comment]
@DMNSteve if anything I can help let me know
```
"jenssegers/mongodb": "3.3.1",
"laravel/framework": "5.5.*",
"laravel/passport": "^4.0",
```

**Comment by majuansari** [comment]
Any particular reason why your pull request is not merged ?

**Comment by DMNSteve** [comment]
Just waiting for it to be reviewed by one of the maintainers. Hopefully, it should be merged soon.

**Comment by DMNSteve** [comment]
@LeonAlvarez, sorry for the delay. Hope you had a Merry Christmas and Happy new year!

I just had a go at this from a fresh Laravel installation and I wasn't able to reproduce the issue
https://github.com/DMNSteve/1390

The only difference is that I'm using my fork at version 3.3.3 https://github.com/DMNSteve/1390/blob/master/composer.json

Might be worth having comparing some of your files with this fresh installation to see if there is anything glaringly obvious.

The user class might be a file of interest https://github.com/DMNSteve/1390/blob/master/app/User.php.

Let me know if you come across anything or would like me to have another go at reproducing

**Comment by LeonAlvarez** [comment]
@DMNSteve I fixed it not sure where was the issue I removed depencies isntaled again and added your files and its working fine now.

**Comment by StevePorter92** [comment]
@majuansari I've closed the initial pull request and moved it to its own package available here https://github.com/StevePorter92/laravel-mongodb-passport

**Comment by dmitov** [comment]
@majuansari @jenssegers A PR, with slightly different approach is added:
https://github.com/jenssegers/laravel-mongodb/pull/1451

**Comment by hosseinjafari24** [comment]
`jenssegers/laravel-mongodb` not supported mongodb connection 
to use passport in laravel with mongodb , you install this package :
https://github.com/designmynight/laravel-mongodb-passport

**Comment by esron** [comment]
Hi, is there any update in this issue? It will be implemented in any near future?

**Comment by Smolevich** [comment]
@esron, You can override main models inherited from laravel database eloquent models on jenssegers models in service provider and use them for work with passport

**Comment by Smolevich** [comment]
I think if you want this feature in laravel mongodb, you can link to slack community and ask maintainer or community. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by esron** [comment]
@Smolevich thank you for your insight. I'll try that.

**Comment by inquisitive-stha** [comment]
@esron did you find any solution for this?

**Comment by esron** [comment]
@inquisitive-stha for now I'm using https://github.com/designmynight/laravel-mongodb-passport.

I didn't have the time to test the models customization .

**Comment by laratuto** [comment]
[it worked for me thanks bro. sure](https://laratuto.com/passport-install-in-laravel/)

**Comment by GromNaN** [comment]
Laravel Passport is supported by [Overriding Default Models](https://laravel.com/docs/11.x/passport#overriding-default-models) with the trait [`MongoDB\Laravel\Eloquent\DocumentModel`](https://www.mongodb.com/docs/drivers/php/laravel-mongodb/v4.x/eloquent-models/model-class/#std-label-laravel-third-party-model).
