### ISSUE TITLE
Change read and write connection

### ISSUE THREAD

**Issue by saeedvz** [mongodb/laravel-mongodb#1496]
How to change read and write host?

        'mongodb' => [
            'read'     => [
                'host' => [env('DB_HOST', 'localhost')],
            ],
            'write'    => [
                'host' => [env('DB_HOST', 'localhost')],
            ],
            'driver'   => 'mongodb',
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options'  => [
                'database' => 'admin' // sets the authentication database required by mongo 3
            ],
        ],

**Comment by felipsmartins** [comment]
I would like to know that also well.

**Comment by zaber04** [comment]
This still not working actually

**Comment by GromNaN** [comment]
Answer in this duplicate issue: https://github.com/mongodb/laravel-mongodb/issues/2728#issuecomment-1948340178
