### ISSUE TITLE
php artisan queue:work mongodb not working

### ISSUE THREAD

**Issue by wiselyku** [mongodb/laravel-mongodb#1515]
hi, 
I use this lib for the job queue.
Right now, it could add the jobs to the queue successfully.
But, when i executed php artisan queue:work mongodb, i got nothing.
Could you tell me what things might be wrong?
Thank you very much.

**Comment by wiselyku** [comment]
BTW, I use version 3.3

**Comment by ypavlov** [comment]
hi @wiselyku, did you solve your problem?
I have the same issue. 
I use mongodb for queues. I could add the jobs to the queue successfully, but php artisan queue:work mongodb not working

**Comment by wiselyku** [comment]
hi, @ypavlov  i did not solve the problem, so i used mysql instead

**Comment by trickyEdecay** [comment]
same here. my project doesn't use any other database but only mongodb. all the dispatched job was added to queue successfully.

when i run `php artisan queue:work`,it print nothing,and shutdown after a while.
and something like this appears in the log:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function beginTransaction() on null in /var/www/html/vendor/illuminate/database/Concerns/ManagesTransactions.php:109
```

**Comment by GromNaN** [comment]
https://jira.mongodb.org/browse/PHPORM-87

**Comment by GromNaN** [comment]
Fixed by https://github.com/mongodb/laravel-mongodb/pull/2838
