### ISSUE TITLE
Gridfs

### ISSUE THREAD

**Issue by kudaibergenoff** [mongodb/laravel-mongodb#1596]
how to use this package with gridfs, can show an example please

**Comment by jmikola** [comment]
This package does not appear to provide special integration with GridFS; however, the [mongo-php-library](https://github.com/mongodb/mongo-php-library)'s GridFS API is accessible and can be used directly. See: https://github.com/jenssegers/laravel-mongodb/issues/826#issuecomment-290362789

**Comment by januzaq** [comment]
understand I need to extract the image from the database and display it on the browser, how can I do it can help or show, please

**Comment by bisht2050** [comment]
GridFS is now supported! 
Follow the docs to learn how to use GridFS : https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/filesystems/
