### ISSUE TITLE
Unique validation fails when validating a subterm of another term

### ISSUE THREAD

**Issue by cincauhangus** [mongodb/laravel-mongodb#1616]
I've encountered an issue when using unique Validator. I'm using Laravel v5.2 & laravel-mongo v3.2.3. The following is the steps to reproduce:

Existing records in database:
```
{'name': "Banking"}
{'name': "Finance and Banking"}
```

Validation rule used: 
```
$this->rules = ['name' => 'unique:brands,name,NULL,_id,deleted_at,NULL'];
```
Data to be validated before inserting: 
```
{'name': "Finance"}
```

Expected validation result should be pass, but instead it failed. Upon further checking, the following line looks for unique value using case-insensitive regex, thus returning values that matches `Finance`, in this case `Finance and Banking`.

https://github.com/jenssegers/laravel-mongodb/blob/bc78c7575b879351eedc4a57b5ac0410ee765b51/src/Jenssegers/Mongodb/Validation/DatabasePresenceVerifier.php#L20

Upon changing to ```$this->table($collection)->where($column, $value);``` will fix the problem

**Comment by GromNaN** [comment]
Fixed by d5f1bb901f3e3c6777bc604be1af0a8238dc089a
