### ISSUE TITLE
MorphToMany

### ISSUE THREAD

**Issue by dilipdk** [mongodb/laravel-mongodb#1685]
MorphToMany relation is not working properly.but MorphedByMany is working well. i cannot get an authenticated user's Roles data.

**Comment by eltonmorais** [comment]
Issue continues to exist several years later.

Even though there's documentation stating the compatibility with Laravel Sanctum. Until you need to list available tokens...

**Comment by GromNaN** [comment]
Please open a new issue describing the issue in details: steps to reproduce, expected result and actual result. 
Thank you for providing actionable feedbacks.
