### ISSUE TITLE
CACHE_DRIVER as Database Returns Call to a member function beginTransaction() on null

### ISSUE THREAD

**Issue by murugesh-smp** [mongodb/laravel-mongodb#1865]
Hi All, 

changing CACHE_DRIVER as database we are getting "Call to a member function beginTransaction() on null". i want to know that laravel-mongodb supports CACHE_DRIVER as database or not.

Is there any way we can achieve this. 

**Reason** why we are using Database as CACHE_DRIVER. 
We are hosting the app in cluster mode. that means we are running 2 parallel application running under LOAD_BALANCER.  In this case, while running a Cron or Scheduler: sometimes it's running twice. that because of the CACHE_DRIVER is in file mode. so it's working along its Individual CACHE files. 

My Cache.php config are 

 'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => 'mongodb',
        ],

And in .env 
CACHE_DRIVER=database

any hint or help will be appreciated.

Many Thanks.

**Comment by Smolevich** [comment]
@murugesh-smp, show test code for reproducing problem

**Comment by GromNaN** [comment]
New `mongodb` cache driver introduced by #2877
