### ISSUE TITLE
Nested date format is different from top level in response

### ISSUE THREAD

**Issue by alexsmko** [mongodb/laravel-mongodb#2129]
- Laravel-mongodb Version: 3.7
- PHP Version: 7.4.9

### Steps to reproduce
1. create model with propery "nested.date"
2. return it as JsonResource for example 
3. you will date in "2020-10-23 09:12:19" format where other dates in "2020-10-23T09:12:19.512000Z"

It looks like $this->serializeDate() should be called in [Mongodb/Eloquent/Model.php#L219](https://github.com/jenssegers/laravel-mongodb/blob/3.7/src/Jenssegers/Mongodb/Eloquent/Model.php#L219) in order to mimic Eloquent's addDateAttributesToArray() in [Eloquent/Concerns/HasAttributes.php#L168](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L168) trait

**Comment by divine** [comment]
Hello,

I see that you've already debugged and found resolution, could you please push a new PR with tests?

Thanks!

**Comment by alexsmko** [comment]
Will try later. Also there is another related bug: new object of such Model fails
```
[2020-10-23 10:50:25] production.ERROR: invalid document for insert: keys cannot contain ".": "last_request.date" {"exception":"[object] (MongoDB\\Driver\\Exception\\InvalidArgumentException(code: 22): invalid document for insert: keys cannot contain \".\": \"last_request.date\" at /src/vendor/mongodb/mongodb/src/Operation/InsertOne.php:132)
```
in my case last_request is null and there is no nested date, didn't dig deep into this,
added this overrides on my model as temporary solution


```
    // Skip setting dotted dates as attribute for new instance
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        foreach ($this->getDates() as $key) {
            if (Str::contains($key, '.')) {
                unset($this->attributes[$key]);
            }
        }
    }

    // Avoid issue with formatting nested dates
    public function attributesToArray()
    {
        $attributes = parent::attributesToArray();
        foreach ($this->getDates() as $key) {
            if (Str::contains($key, '.') && Arr::has($attributes, $key)) {
                Arr::set($attributes, $key, $this->serializeDate($this->asDateTime(Arr::get($attributes, $key))));
            }
        }
        return $attributes;
    }
```

**Comment by MeerKatDev** [comment]
I'm having the same issue, was it merged so far?

**Comment by divine** [comment]
> I'm having the same issue, was it merged so far?

No, that's the reason why this issue is still open.

Thanks.

**Comment by divine** [comment]
Hello @alexsmko ,

Yes, you're right indeed, it doesn't start the test. Docker compose file needs to be updated as well, would you like to help? 😉 

 Thanks!

**Comment by avivais** [comment]
This is still an issue:
1. Whenever I try to set a field that's not included in `$dates` array with `Carbon` value, it results with an empty object
1. When I try to add `nested.date` field and set it to a `Carbon` value, it's also saved as an empty object

Any workaround? Sometthing I might be missing?

**Comment by GromNaN** [comment]
Fixed by https://github.com/mongodb/laravel-mongodb/pull/3105
