### ISSUE TITLE
Job Batching not Working

### ISSUE THREAD

**Issue by garissman** [mongodb/laravel-mongodb#2144]
- Laravel-mongodb Version: v3.8.1
- PHP Version: 7.4.9
- Laravel Version: v8.15.0
- Database Driver & Version: jenssegers/mongodb  v3.8.1

### Description:
Trying to get property 'id' of non-object
on vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php:256
### Steps to reproduce
1. Just create the Bus like:
```php
use App\Jobs\ProcessPodcast;
use App\Podcast;
use Illuminate\Bus\Batch;
use Illuminate\Support\Facades\Bus;
use Throwable;

$batch = Bus::batch([
    new ProcessPodcast(Podcast::find(1)),
    new ProcessPodcast(Podcast::find(2)),
    new ProcessPodcast(Podcast::find(3)),
    new ProcessPodcast(Podcast::find(4)),
    new ProcessPodcast(Podcast::find(5)),
])->then(function (Batch $batch) {
    // All jobs completed successfully...
})->catch(function (Batch $batch, Throwable $e) {
    // First batch job failure detected...
})->finally(function (Batch $batch) {
    // The batch has finished executing...
})->dispatch();
```

### Expected behaviour
in Illuminate\Bus\DatabaseBatchRepository::find
```php
$batch = $this->connection->table($this->table)
                            ->where('id', $batchId)
                            ->first();
// $batch should be a object instead of array
if ($batch) {
// the error is trigger by this method "toBatch"
    return $this->toBatch($batch);
}

    protected function toBatch($batch)
    {
        return $this->factory->make(
            $this,
            $batch->id, // this $batch is a array and not a object
            $batch->name,
            (int) $batch->total_jobs,
            (int) $batch->pending_jobs,
            (int) $batch->failed_jobs,
            json_decode($batch->failed_job_ids, true),
            unserialize($batch->options),
            CarbonImmutable::createFromTimestamp($batch->created_at),
            $batch->cancelled_at ? CarbonImmutable::createFromTimestamp($batch->cancelled_at) : $batch->cancelled_at,
            $batch->finished_at ? CarbonImmutable::createFromTimestamp($batch->finished_at) : $batch->finished_at
        );
    }
```

### Actual behaviour
in Illuminate\Bus\DatabaseBatchRepository::find
```php
$batch = $this->connection->table($this->table)
                            ->where('id', $batchId)
                            ->first();
// it returns a array and not a object
```

Thanks

**Comment by MartMoiseev** [comment]
Same problem! Try on MongoDB and MySQL.

**Comment by NiekNijland** [comment]
Same problem here:
![afbeelding](https://user-images.githubusercontent.com/43474728/129320924-44eff76b-c1c0-40e0-ad25-584a9de72cd8.png)

![afbeelding](https://user-images.githubusercontent.com/43474728/129320988-ed8a44d7-9297-4d56-9b07-831f9499da8c.png)

**Comment by stadeleon** [comment]
The same issue

**Comment by stadeleon** [comment]
if make this fix than got next error
![image](https://user-images.githubusercontent.com/5434115/129805996-3999b199-201d-427b-a104-7998cbb10986.png)
![image](https://user-images.githubusercontent.com/5434115/129806078-810b387d-14af-4c7c-9740-4bfce9a2a10f.png)

**Comment by Giacomo92** [comment]
Hi @stadeleon, in order to fix this issue this PR #1904 has to be merge

**Comment by alameenpa** [comment]
Bus::batch will not work with MongoDB. 

Currently not supporting, may be in feature releases.

**Comment by AlifAbhiesa** [comment]
Is any progress about this issue?

**Comment by puuble** [comment]
Same :( 

> Is any progress about this issue?

**Comment by d-uvin** [comment]
Try to extend that DatabaseBatchRepository in providers by creating custom class with redeclared find() method

**Comment by oktaykalfa** [comment]
Hello, this problem still persists. Is there any update?

Laravel version: 8.83.23
PHP version:  8.1.6
Laravel-mongodb Version: v3.8.1
Database Driver & Version: jenssegers/mongodb v3.8.1

**Comment by masitings** [comment]
Is there any update for batching ? i've try hybrid using mysql for batches only. What i do is i change the config of queue where there is a batch array says 'batching' . It work for creating the batch, but im not sure all the queue goes to mongodb instead. Really need batching to be worked!

**Comment by alcaeus** [comment]
I see a couple of problems using the default `DatabaseBatchRepository` class:
1. The class uses `id` for its primary key, but MongoDB uses `_id`. This makes all queries on `id` unindexed
2. The above also causes the `id` property to have no unique constraint unless people run a migration for that collection
3. The query builder returned by the `->table()` call uses a type map specifying arrays for root documents and embedded documents. This causes the issue of receiving an array when the repository expects an object. However, this is not something we can generally change.

With that in mind, the solution will most likely involve creating a separate repository class that doesn't have the issues mentioned above.

**Comment by puuble** [comment]
same :(  this issue opened 2020 and now 2024.  Pls fix it. We cant make batch on MongoDB how to do this? Why laravel doesnt focus to mongodb ?

**Comment by bisht2050** [comment]
We are actively working on this. Please follow [PHPORM-81](https://jira.mongodb.org/browse/PHPORM-81) for updates.

**Comment by puuble** [comment]
> We are actively working on this. Please follow [PHPORM-81](https://jira.mongodb.org/browse/PHPORM-81) for updates.

I found a solution for this. I created Sqlite and i use for job_batches on it. This is work for me.

**Comment by azhard4int** [comment]
+1 for this.

**Comment by bisht2050** [comment]
Job Batching was added with v4.4
Check out the documentation here - https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/queues/#job-batching
