### ISSUE TITLE
Reseting int keys.

### ISSUE THREAD

**Issue by erblinbobaj** [mongodb/laravel-mongodb#2147]
- Laravel-mongodb Version: ^3.7
- PHP Version: 7.3
Hi i am having a problem when i am doing

`Test::create([
    "name" => "test",
    "2020" => ["12" => "example"]
]);`
Mongo package resets 2020 to 0 and gives me the response 
`{
    "name": "test",
    "0": {
        "12": "example"
    }
}`
Is there anyway i can avoid this?

**Comment by Smolevich** [comment]
@erblinbobaj what version of mongodb package(please `<major_version>.<minor_version>.<release_version>`)

**Comment by holla-liuyang** [comment]
the same problem for  3.8.5

**Comment by GromNaN** [comment]
This issue with numerical field names needs to be fixed in Eloquent first. See https://github.com/mongodb/laravel-mongodb/issues/2683
