### ISSUE TITLE
Cannot get chunking to work

### ISSUE THREAD

**Issue by nicolasvahidzein** [mongodb/laravel-mongodb#2337]
Hello,

I am not getting any results when trying to use the chunk method. Would it be possible to have an example of chunking applied to a query please?

Thank you very much for your assistance.

**Comment by 0xSheff** [comment]
+1

here's my example:

`
$res = collect();

        self::where('type', EventType::PAGE_VIEW)
            ->where('date', '>=', $startDate)
            ->where('date', '<=', $endDate)
            ->chunk(1000, function($events) use ($res) {
                foreach ($events as $event) {
                    $res->push($event);
                }
            });

dd($res);
`

and it just do nothing, like it stucks. If I dump it inside callback after foreach - it shows the chunk, collection of 1000, but it doesn't go forward

**Comment by nicolasvahidzein** [comment]
It works for me, please remind me in a few hours I am busy but i can help you with this.

**Comment by 0xSheff** [comment]
Yes, it takes more time than I expected, but it works. I just had to wait more :) 
So the issue can be solved, it seems

**Comment by nicolasvahidzein** [comment]
I do this and it works great

```
		//set the batch size for this job
		$batch_size = 200;
		
		ProductsDetails::query()
		->where('seller_uid', '=', $seller->UID)
		->where('locations.location', '=', $locationUid)
		->chunk($batch_size, function ($records) use (&$file, $locationUid, $appUrl, $locationToProcess) {
			
			foreach ($records as $key => $productDetails) {
				Log::channel('merlin_debug')->info('$key:');
				Log::channel('merlin_debug')->info($key);
				Log::channel('merlin_debug')->info('$productDetails:');
				Log::channel('merlin_debug')->info($productDetails);
				
				//DO SOMETHING;
				
				}
				
			}
			
		});
```

**Comment by cys2best** [comment]
I got the same issue, it seems like it stucks at the second batch.

**Comment by nicolasvahidzein** [comment]
strange, working great on my end buddy. What version of the package are you using?
