### ISSUE TITLE
Pushing an array to an array shows each element in the array as children, but it is inserted and fetched as expected

### ISSUE THREAD

**Issue by ghost** [mongodb/laravel-mongodb#2387]
- Laravel-mongodb Version: 3.9.0
- PHP Version: 8.0.17
- Database Driver & Version:

### Steps to reproduce
1. Push to an array
2. Return the parent entity as json response
3. See the items pushed are shown as each pushed.
4. Do a GET for that entity, the item is shown as expected.

### Expected behaviour
It should be consistent between the after-update and the re-fetch

### Actual behaviour
The output is different from the fetch (and how it looks in the DB) from the after-update state

Example:

```
public function addProduct(ProductAddRequest $request, $purchaseRequestId): Response|JsonResponse
    {
        /** @var PurchaseRequest|null $purchaseRequest */
        $purchaseRequest = PurchaseRequest::find($purchaseRequestId);

        if (!$purchaseRequest) {
            return new Response("", HttpCodes::NOT_FOUND);
        }

        $product = new Product(
            $request->request->get('currency'),
            $request->request->get('unit_cost'),
            $request->request->get('product_id'),
            $request->request->get('quantity'),
        );

        $purchaseRequest->push('products', $product->toArray());   // <---------- here

        return new JsonResponse($purchaseRequest);
    }
```

output when adding an item:

```
{
    "id": "62862f04375eed096c6abc32",
    "products": [
            "id": "628667dccee1aa7afe760d24",
            "currency": "MXN",
            "unit_cost": 15999,
            "product_id": 1,
            "quantity": 1,
            "metadata": []
    ]
}
```

output when fetching the same item

```
{
    "id": "62862f04375eed096c6abc32",
    "products": [
        {
            "id": "628667dccee1aa7afe760d24",
            "currency": "MXN",
            "unit_cost": 15999,
            "product_id": 1,
            "quantity": 1,
            "metadata": []
        },
   ]
}
```

Note: It can be fixed by wrapping the array into a new array. Then it inserts as before, and also shows correctly in the current loaded entity.

**Comment by hans-thomas** [comment]
The behavior of the `push` method is quite correct. It pushes an array of values to the given key. if you want to push an array, you must wrap your array with an array. So the `push` method pushes your array as a value.

**Comment by hans-thomas** [comment]
@GromNaN I was reading the docs and I faced this [section](https://github.com/mongodb/laravel-mongodb/blob/4.1/docs/query-builder.md). I think the reason for confusion about the `push` or `pull` methods is the docs.
These are the provided examples in the docs for the `push` method.
```php
$user->push('items', 'boots');
// Or
$user->push('messages', [
    'from' => 'Jane Doe',
    'message' => 'Hi John',
]);
```
The second example is incorrect. If we want to push an array as a value, we must wrap it with an array. The correct examples can be these.
```php
$user->push('items', 'boots');
// Or
$user->push('items', [ 'batsuit', 'cape' ]);
// Or
$user->push('messages', [
    [
        'from' => 'Jane Doe',
        'message' => 'Hi John',
    ]
]);
```

**Comment by GromNaN** [comment]
Good point. Wrapping a single element is done with `Arr::wrap`, but not when passing an array.
In fact, it could be detected if a list is passed. But this is problematic if they want to work with numerical field names.

https://github.com/mongodb/laravel-mongodb/blob/1c2d1fe29a53278ec34a50c1a289b5e3a8f1a838/src/Eloquent/Model.php#L470

Let’s fix the documentation. You can also add a preview of the stored document before and after to make things explicit, I find that the difference between `push` and `pull` is not obvious when looking at these examples.

**Comment by hans-thomas** [comment]
Okay then, I will open a PR later to update the docs.

**Comment by jmikola** [comment]
> But this is problematic if they want to work with numerical field names.

@GromNaN: Not just numerical field names. There are valid use cases for storing an array of arrays (referring to actual BSON arrays, not PHP HashTables). To that end, a more self-documenting method name might be `pushValues` where it's clear the arguments are a list of values to be pushed. Not sure if there's still an opportunity to do that, though, since this method has existed for some time.

**Comment by Disguise-rehan** [comment]
> Okay then, I will open a PR later to update the docs.





https://preprocessor.space/questions/what-is-the-best-way-to-retrieve-a-specific-element-from-a-mongodb-array
