### ISSUE TITLE
Rename column in migration has no effect

### ISSUE THREAD

**Issue by flappix** [mongodb/laravel-mongodb#2391]
- Laravel-mongodb Version: 3.8
- PHP Version: 8.1.16
- Database Driver & Version: MongoDB 4.4.14, mongodb php driver 1.13.0

### Description:

When I try to rename a field of a collection within a migration using ```$table->renameColumn()``` the migration runs without errors but the fields in the collection have the same name as before running the migration 

### Steps to reproduce

Collection users:
```
{
    _id: 62859365a1767a00c9589712,
    name: "admin",
    role: "member"
}
```
Migration file:

```
class RenameUser extends Migration
{
    public function up()
    {
		Schema::table ('users', function (Blueprint $table) {
			$table->renameColumn ('role', 'global_role');
		});
    }
}
```

```> php artisan migrate```

### Expected behaviour

I expected the same behavior as running the following monogdb command
```db.users.updateMany ({},{ $rename: { 'role': 'global_role'}} )```
The name of the field ```role``` should be ```global_role``` after running the migration.

### Actual behaviour
Nothing, no error but also no effect.

**Comment by JasperDirsha** [comment]
I'm also getting the same error, No error but renaming has not happened. 
@flappix did you get any solution for this?

**Comment by flappix** [comment]
No, I think the schema builder is not capable of doing this. You could use a raw query instead instead of the schema builder like

```
public function up()
    {
		 DB::collection('users')->update([
            '$rename'=>['role'=> "global_role"],
        ]);
    }
```
