### ISSUE TITLE
What's the equivalent of SELECT COUNT(column_name)?

### ISSUE THREAD

**Issue by Gabsys** [mongodb/laravel-mongodb#2392]
How can we retrieve the size of an array in the `get()` function?

Update: Ultimately, I want to get the size of the array column for each qualified document

Example, for each document, I have an array of members data. Therefore, I would like to know for each document, how many members are there.

From Laravel's perspective, I could just load the entire member list for all qualified records and use count() to get the array size in blade template. But I wanna avoid that because it will cause loading issue if the member list for each record is huge.

**Comment by GromNaN** [comment]
Feature request tracked in PHPORM-117

**Comment by GromNaN** [comment]
I just found we have the `Query::project()` method that allows to use expression operators in projection. Using [`$size`](https://www.mongodb.com/docs/manual/reference/operator/query/size/), you get the number of elements in the array field.

```php
User::insert([
    ['name' => 'John Doe', 'items' => [1, 2, 3, 4]],
    ['name' => 'Jane Doe', 'items' => [1, 2, 3, 4, 5]],
    ['name' => 'Jonny Doe', 'items' => []],
]);

$result = User::project(['itemsCount' => ['$size' => '$items']])->get();

var_dump($result[0]->itemsCount); // 4
var_dump($result[1]->itemsCount); // 5
var_dump($result[2]->itemsCount); // 0
```
