### ISSUE TITLE
schema default value not working

### ISSUE THREAD

**Issue by webafra** [mongodb/laravel-mongodb#2400]
- Laravel-mongodb Version: 9
- PHP Version: 8
- Database Driver & Version: latest

### Description:
```
Schema::create('my_doc', function (Blueprint $collection) {
            $collection->id();
            $collection->string('title')->default('test');
            $collection->timestamps();
        });
```

When a record is stored without a title value, the title field value is empty.

**Comment by hans-thomas** [comment]
It's a schemaless database and migrations do not work at all. try to use `$casts` for casting your data types and `$attributes` for setting default values.

**Comment by GromNaN** [comment]
I confirm that you can set default values un `$attributes` property, as mentioned in the doc.
https://laravel.com/docs/10.x/eloquent#default-attribute-values

This defaults will not be used when the bulk method `Model::insert()` is used.

> The schema validation is only intend to enforce/validate a schema definition and not populate values.
> If you use Atlas you can consider having a trigger on the collection to update every inserted document with a specific filed value. This is the same behavior for Eloquent SQL.

https://www.mongodb.com/community/forums/t/setting-default-values-in-data-schema/8411/2?u=jerome
