### ISSUE TITLE
Spatie's QueryBuilder support

### ISSUE THREAD

**Issue by leon0399** [mongodb/laravel-mongodb#2409]
- Laravel-mongodb Version: 3.9.9
- PHP Version: 8.1.0
- Database Driver & Version: 

### Description:
Queries, populated with Spaties's query builder are not correct. 
Spatie's package adds table prefix for WHERE filters: `select * from table 'example' ... where 'example'.'column' = ?`
MongoDB driver can not execute such queries, as it interprets this query as deep object comparison (`{ "example": { "column": "value" } }`) instead of `{ "column": "value" }`

Adding table (or collection) prefix to query is correct behavior and part of Model function: ``

Temporal fix is adding this to your model:

```php
    public function qualifyColumn($column)
    {
        return Str::after($column, $this->getTable() . '.');
    }
````

### Steps to reproduce
1. `composer require spatie/query-builder`
2. Create MongoDB model
3. ```php
    QueryBuilder::for(MongoModel::class)
      ->allowedFiilter([
        AllowedFilter::exact('column'),
      ])
      ->dd();
    ```
4. `/some-route?filter[column]=value`

### Expected behaviour
```
{
  "$and": {
    "column": "value",
  }
}
```

### Actual behaviour
```
{
  "$and": {
    "mongo-model.column": "value",
  }
}
```

**Comment by GromNaN** [comment]
Thank you for the feature request. The proposed fix seems correct as we never have to prefix the field name with the collection name in MongoDB.

The effect of `Illuminate\Database\Eloquent::qualifyColumn()` must be cancelled. Doing this change, we will have to validate that this doesn't affect hybrid relationships.
https://github.com/laravel/framework/blob/0ff1229c4bbcd8e63fe1c0f3d295415dfa7d51fa/src/Illuminate/Database/Eloquent/Model.php#L561-L574

Tracked in PHPORM-119
