### ISSUE TITLE
Unable to fetch relationships withThrashed

### ISSUE THREAD

**Issue by galzetta** [mongodb/laravel-mongodb#2423]
### Description:

withThrashed doesn't work at all.

### Steps to reproduce
1. Define an entity relationship like so:
    ```
    public function something()
        {
            return $this->belongsTo(Something::class)->withThrashed();
        }
    ```
2. Call this method

### Expected behaviour

The results are returned and they include thrashed objects.

### Actual behaviour

An exception is raised:

```
BadMethodCallException in Builder.php line 2450: Call to undefined method Jenssegers\Mongodb\Query\Builder::withThrashed()
```

**Comment by GromNaN** [comment]
Works as expected.
