### ISSUE TITLE
[Feature Request] Bulk Upsert

### ISSUE THREAD

**Issue by robertfels** [mongodb/laravel-mongodb#2434]
### Is your feature request related to a problem?
Yes, i can not upload bulk messages via upsert

### Describe the solution you'd like
I would like to use ELO **insertOrIgnore** or **upsert** with array, but this is not implemented

### Describe alternatives you've considered
I have currently no workaround. Single upsert takes too much time

**Comment by DishantPal** [comment]
plz ref: https://github.com/jenssegers/laravel-mongodb/issues/2266#issuecomment-1253636306

**Comment by GromNaN** [comment]
Closing as duplicate of #2266

**Comment by GromNaN** [comment]
Closing as duplicate of https://github.com/mongodb/laravel-mongodb/issues/2266
