### ISSUE TITLE
[Doc Improvement Request] Laravel Sanctum Configuration

### ISSUE THREAD

**Issue by ricardoaranha96** [mongodb/laravel-mongodb#2445]
I believe that the comment in the link below should be at least referenced in the docs. 

[https://github.com/jenssegers/laravel-mongodb/discussions/2242#discussioncomment-678732](https://github.com/jenssegers/laravel-mongodb/discussions/2242)

It basically creates a new PersonalAccessToken class that can be used to make Sanctum work with MongoDB. I struggled with the same problem that the issue author had and I believe that this solution could help more people if it becomes easier to find or becomes part of the official docs.

**Comment by jessetmia** [comment]
A ticket has been created to address this issue: https://jira.mongodb.org/browse/PHPORM-88

**Comment by GromNaN** [comment]
If you have a clear idea of what and how to document, please create a pull-request.
