### ISSUE TITLE
[Feature Request] Int32 and Int64

### ISSUE THREAD

**Issue by nonrk** [mongodb/laravel-mongodb#2453]
PHP to Mongodb field set Int32 or Int64

**Comment by alcaeus** [comment]
The PHP driver automatically stores any 64-bit value as a BSON 64-bit integer. To explicitly store a 32-bit value as 64-bit integer in BSON, you can use the `MongoDB\BSON\Int64` class starting with version 1.16 of `ext-mongoldb`.
