### ISSUE TITLE
LIKE breaks when the search condition ends with \

### ISSUE THREAD

**Issue by RichuJohn** [mongodb/laravel-mongodb#2475]
In \Jenssegers\Mongodb\Query\Builder::compileWhereBasic,  https://github.com/jenssegers/laravel-mongodb/blob/e5e91936b7537354672df27e7cfbeec7fa2fb2d1/src/Query/Builder.php#L1046 

This was added as a fix for https://github.com/jenssegers/laravel-mongodb/issues/719

the regex explicitly looks for pattern that starts with % or having a percentage that is just after any character but a backslash.

Could you please provide the reason why that was implemented like this. I am trying to search in mongodb for a substring that ends with backslash and it doesn't generate the correct regex.

would you agree a more generic regex like `'#(^|.)%#'` is more suited here?

**Comment by ming-xu-xxx** [comment]
Same problem here #2458.  It looks like the keyword ending with a backslash or a single backslash as the keyword will not be replaced by the pattern properly.

**Comment by RichuJohn** [comment]
Understood the alternator used here is to avoid replacing escaped %. So added another alternator that avoids replacing any \ that is not followed by a % and end of string, so that only the backslash at the end of the search query is targeted and replaced.

**Comment by GromNaN** [comment]
Fixed by https://github.com/mongodb/laravel-mongodb/commit/ea89e8631350cd81c8d5bf977efb4c09e60d7807

**Comment by GromNaN** [comment]
I would recommend using using regex directly as you get more control over the query. The `like` operator is implemented for compatibility with Eloquent.

```
use MongoDB\BSON\Regex;
Model::where('field', new Regex('/text.*/', 'i'))->get();
```
