### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by wo642436249** [mongodb/laravel-mongodb#2491]
- Laravel-mongodb Version: #.#.#
- PHP Version: 8.2.0
- Database Driver & Version:3.4.4

### Description:
i don t speak englinsh，so zhi tie chu le  baocuo xinxi
### Steps to reproduce
1.ErrorException: Use of "parent" in callables is deprecated in /www/webman/vendor/jenssegers/mongodb/src/Query/Builder.php:900
2.ErrorException: Use of "parent" in callables is deprecated in /www/webman/vendor/jenssegers/mongodb/src/Query/Builder.php:900
3.ErrorException: Use of "parent" in callables is deprecated in /www/webman/vendor/jenssegers/mongodb/src/Query/Builder.php:900

### Expected behaviour
ErrorException: Use of "parent" in callables is deprecated in /www/webman/vendor/jenssegers/mongodb/src/Query/Builder.php:900

### Actual behaviour
ErrorException: Use of "parent" in callables is deprecated in /www/webman/vendor/jenssegers/mongodb/src/Query/Builder.php:900

<details><summary><b>Logs</b>:</summary>
ErrorException: Use of "parent" in callables is deprecated in /www/webman/vendor/jenssegers/mongodb/src/Query/Builder.php:900
</details>

**Comment by ebinwik** [comment]
I am also facing the same issue on my project. Have you found the fix for this? It will be helpful if you share the solution. Thanks in advance.
@wo642436249

**Comment by GromNaN** [comment]
Hello @ebinwik what version of this library are you using?
You can run `composer show jenssegers/mongodb` to get it.
