### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by beeyev** [mongodb/laravel-mongodb#2500]
Firstly, thank you so much for the great package, I have been using it for quite a long, and it's absolutely great.

I have a question, since Laravel 10 will be released very soon, on February 7th. Will this package support the new Laravel version?

**Comment by saeeddarestany** [comment]
+1

**Comment by GromNaN** [comment]
Hello, do you know what have to be done to support Laravel 10?

**Comment by idrisalshikh** [comment]
I tried to upgrade my project from laravel 9 to 10 and get this error
 Problem 1
    - Root composer.json requires jenssegers/mongodb ^3.9 -> satisfiable by jenssegers/mongodb[v3.9.0, ..., v3.9.4].
    - jenssegers/mongodb[v3.9.0, ..., v3.9.4] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.0] but these were not 
loaded, likely because it conflicts with another require.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require jenssegers/mongodb:*" to figure out if any version is installable, or "composer require jenssegers/mongodb:^2.1" if you know which you need.

**Comment by alcaeus** [comment]
Laravel 10 support hasn't been released yet. You'll have to update your composer.json to use dev-master if you want to test it. Please be aware that there will likely be further BC breaks until we release a new version with Laravel 10 support.

**Comment by Wernke96** [comment]
I just want to say there will be a release for laravel 10 for major update releases it usually takes a couple of days to get a new tag out. Right now the support for 10 has already been merged into the master just need to get tagged and maybe update some docs but it will be out soon enough.

**Comment by liamka** [comment]
?

**Comment by divine** [comment]
I have locked up this issue to prevent further SPAM.

Laravel 10 support will be released whenever it’s stable enough. If you’d like to test it out use dev-master version.

Thanks!

**Comment by GromNaN** [comment]
Alpha version released: [v4.0.0-ALPHA2](https://github.com/mongodb/laravel-mongodb/releases/tag/v4.0.0-ALPHA2)

**Comment by GromNaN** [comment]
The `mongodb/laravel-mongodb` [4.0.0](https://github.com/mongodb/laravel-mongodb/releases/tag/4.0.0) have been release with Laravel 10 support.

Thank you for your patience.
