### ISSUE TITLE
Deleting With Limit Doesn't Work

### ISSUE THREAD

**Issue by ceater-sigma** [mongodb/laravel-mongodb#2502]
- Laravel Version: 9
- PHP Version: 8.0
- MongoDB Version: 3.9

### Description:
Hello, i have problem when deleting data using where + limit. Even using limit is not working. The command didn't use the limit parameter.

### Steps to reproduce
BalanceModel::where('time', '<=', 1670707849677)->take(1)->delete();

### Expected behaviour
Delete BalanceModel where time < xxxx limit 1

### Actual behaviour
When i run that command, it delete using time parameter and delete document without limiting the delete command

The Current Operation Image Status
![image](https://user-images.githubusercontent.com/119039185/215754708-604ebefb-a92d-46b0-acdd-2577a13fe47a.png)
![image](https://user-images.githubusercontent.com/119039185/215754891-90d9192c-eded-47e3-9d50-00b7ff1fb9b7.png)

**Comment by GromNaN** [comment]
You can look at the proposed fix: https://github.com/mongodb/laravel-mongodb/pull/2591
