### ISSUE TITLE
Validating unique case insensitive

### ISSUE THREAD

**Issue by emanuelones** [mongodb/laravel-mongodb#2518]
- Laravel-mongodb Version: 3.9.5
- PHP Version: 8.1

I'm using the laravel validator rule `unique` in order to make sure that the given category name doesn't already exist. Problem is that it is not case insensitive therefore `Foo` and `foo` are not seen as unique (guess they aren't). 
 
This is my `rules` array:

    [
        'name' => ['required','unique:categories']
    ];

Is there a way to check case insensitive? 

Thank you!

**Comment by KinyuaMwaniki** [comment]
Hi @emanuelones ,

Did you ever get a work around to solve this?

**Comment by GromNaN** [comment]
We use `i` flag in the regex so the unique constraint is case-insensitive.
https://github.com/mongodb/laravel-mongodb/blob/1af8b9dcfe336c83b0aa8f09193747129c2bb663/src/Validation/DatabasePresenceVerifier.php#L28

You can submit a pull request to the [ValidationTest](https://github.com/mongodb/laravel-mongodb/blob/4.0/tests/ValidationTest.php) if you can reproduce the error.
