### ISSUE TITLE
Can't filter by date

### ISSUE THREAD

**Issue by frenchqwerty** [mongodb/laravel-mongodb#2529]
- Laravel-mongodb Version: 3.9.5
- PHP Version: 8.2

### Description:

I have a date array and I want to retrieve those that are an interval.

For example: Retrieve me those with a date between 2023-03-01 and 2023-03-31

### Steps to reproduce

My collection is presented :

```
"departures": [
			"2022-10-23T23:30:00.000+00:00", // Date object
                         "2023-02-02T23:30:00.000+00:00",
                         "2023-11-10T18:00:00.000+00:00"
		],
		"price": 310,
```

```
$beginDate = Carbon::createFromFormat("Y-m-d", "2023-03-01");
$endDate = clone $beginDate;
$endDate->endOfMonth();
                
$search->whereBetween('departures', [$beginDate->toDateTime(), $endDate->toDateTime()])->get()->toArray();
```

### Expected behaviour
It must return me an empty array.

### Actual behaviour
It returns me all the table.

**Comment by puuble** [comment]
Hi you can use 
`protected $dates = ['startDate', 'endDate'];
$d = WorkPeriod::where('startDate', '>=', Carbon::parseFromLocale($this->start))->where('endDate','<=',Carbon::parseFromLocale($this->end));
`
$this->start = can be string no problem with `parseFromLocale`

**Comment by GromNaN** [comment]
Thanks for the correct answer.
`$dates` is now replaced by `$casts`.
