### ISSUE TITLE
empty result meilisearch

### ISSUE THREAD

**Issue by ithuis** [mongodb/laravel-mongodb#2541]
i get empty result in my meilisearch results. The raw results work fine. 

i found that the error is in the 
class "Laravel\Scout\Searchable"
function "queryScoutModelsByIds"

where it says
`$this->qualifyColumn($this->getScoutKeyName()), $ids`

the "qualifyColumn" returns for example 'users'.'_id'. This will not work in a query using this module. 

i dont know enough about mongodb to understand the impact of my proposal. 
But it seems that adding a function like

`  /**
     * Qualify the given column name by the model's table.
     *
     * @param  string  $column
     * @return string
     */
    public function qualifyColumn($column)
    {
        return $column;
    }`

to the Jenssegers\Mongodb\Eloquent\Model class would fix it

( for now i added the function to my user model.)

**Comment by hans-thomas** [comment]
@GromNaN Please close this since It's fixed in #2676.
