### ISSUE TITLE
Laravel 9 Unexpected datetime behaviour on Null datetime field

### ISSUE THREAD

**Issue by cyberdude4** [mongodb/laravel-mongodb#2553]
- Laravel-mongodb Version: 9
- PHP Version: 8.2
- Database Driver & Version:

### Steps to reproduce
1. Create/store null or empty datetime field in collection
2. add this datetime field in collection model in protected $cast array 
3. try to fetch data from collection
4. and check null date will show as Current date

### Expected behaviour
After fetching data from collection the Null or empty date fields should return null value or empty value - not current datetime 

### Actual behaviour
Insted of return null or empty field it returning current datetime

**Comment by GromNaN** [comment]
I added a test but did not hit the bug #2592
