### ISSUE TITLE
Error executing whereNot 

### ISSUE THREAD

**Issue by stescacom** [mongodb/laravel-mongodb#2623]
- Laravel-mongodb Version: 4.0.0-rc1
- PHP Version: 9.1
- Database Driver & Version: 6.0.4

### Description:
Executing whereNot query throws error: `unknown top level operator: $not. If you are trying to negate an entire expression, use $nor.`

**Comment by GromNaN** [comment]
Hello, could you share the PHP code of the query you are trying, so that we can fix the generated query.
