### ISSUE TITLE
Call to a member function prepare() on null when i try to seed data into mongodb in laravel

### ISSUE THREAD

**Issue by wawerukaranja55** [mongodb/laravel-mongodb#2630]
- Laravel-mongodb Version: 5.0
- PHP Version: 8.1
- Database Driver & Version:1.30

### Description:
am trying to seed data into mongodb database but am gettng this error "Call to a member function prepare() on null".

here is the Role Model

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Helpers\EloquentBuilder;

class Role extends Model
{
    use HasFactory;

    protected $connection = 'mongodb';

    protected $collection = 'roles';

    protected $fillable=['role_name'];

    protected $guarded = ['_id'];
}

while this is the Role seeder

use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

            Role::create(['Role_name'=>'Admin']);
            Role::create(['Role_name'=>'Writer']);
        
    }
}

am not sure where the error is coming from as i have followed all the guidelines in the documentati
![Captureww23q](https://github.com/mongodb/laravel-mongodb/assets/107123993/548d41df-f2ce-41a5-9eda-04958ab71134)
on.how can i fix this

**Comment by jmikola** [comment]
@wawerukaranja55: If you identified and solved the problem on your own, it'd be helpful to share the solution for the benefit of others that might come across this issue down the line.

**Comment by waweru-karanja** [comment]
I fixed the issue by changing from class Role extends model to class Role extends Eloquent 

Then at the top I added

Use jenssengers/mongodb/eloquent/model as eloquent
